export const FETCH_FORECAST_START = "FETCH_FORECAST_START"
export const FETCH_FORECAST_SUCCESS = "FETCH_FORECAST_SUCCESS"
export const FETCH_FORECAST_FAILED = "FETCH_FORECAST_FAILED"

export const FETCH_WEATHER_DATA_START =  "FETCH_WEATHER_DATA_START"
export const FETCH_WEATHER_DATA_SUCCESS =  "FETCH_WEATHER_DATA_SUCCESS"
export const FETCH_WEATHER_DATA_FAILED =  "FETCH_WEATHER_DATA_FAILED"